set(CMAKE_CXX_FLAGS
    "${CMAKE_CXX_FLAGS}
    -g
    -pthread
    -fuse-ld=lld
    -fstandalone-debug
    -Wextra
    -fcolor-diagnostics
    -fparse-all-comments
    -stdlib=libc++
    -std=c++20
    --target=x86_64-w64-mingw"
    )